########################
# General Settings     #
########################
settings:
  inventory-title: "&8Cheque Menu"
  default-cheque-price: 1000
########################
# Custom Messages      #
########################
messages:
  console: "&cOnly players can use this command!"
  inventory-full: "ยง&Your inventory does not have enough space to create a cheque, please try again!"
  canceled: "&cProcess successfully canceled!"
  invalid-number: "&cCould not identify the number, please try again!"
  no-money: "&cYou don't have &2$&f<amount> &cto create a cheque right now!"
  success: "&aYour &2$&f<amount> &acheque has been created successfully!"
  release-shift: "&cRelease shift to interact with inventory!"
  type: "&aType the value of the cheque to be created, to cancel this process type '&7cancel&a' in the chat."
  use-cheque: "&aYAY! &2$&f<amount> &ahas been successfully deposited into your bank account!"
  no-permission: "&cYou don't have permission to execute this command!"

